"""Copy UI Files generated by EEZ Studio"""

import os
import shutil
import sys

SOURCE_DIR = os.path.join("..", "eez-studio", "src", "ui")
TARGET_DIR = os.path.join("components", "ui")

# Check if source directory exists
if not os.path.exists(SOURCE_DIR):
    print(f"Error: Source directory '{SOURCE_DIR}' does not exist.")
    sys.exit(1)

# Remove target directory if it exists to ensure a clean copy
if os.path.exists(TARGET_DIR):
    try:
        shutil.rmtree(TARGET_DIR)
        print(f"Removed existing directory: {TARGET_DIR}")
    except Exception as e:
        print(f"Error removing {TARGET_DIR}: {e}")
        sys.exit(1)

# Create target directory
try:
    os.makedirs(TARGET_DIR)
    print(f"Created directory: {TARGET_DIR}")
except OSError as e:
    print(f"Error creating {TARGET_DIR}: {e}")
    sys.exit(1)

# Copy files
files_copied = 0
try:
    for filename in os.listdir(SOURCE_DIR):
        if filename.endswith(".c") or filename.endswith(".h"):
            source_file = os.path.join(SOURCE_DIR, filename)
            target_file = os.path.join(TARGET_DIR, filename)

            shutil.copy2(source_file, target_file)
            print(f"Copied: {filename}")
            files_copied += 1
except Exception as e:
    print(f"Error listing or copying files: {e}")
    sys.exit(1)

print(f"Successfully copied {files_copied} files.")
